### ISSUE TITLE
UI changes in done() are not shown in browser

### ISSUE THREAD

**Issue by JohannesDorn** [mpilone/uitask-vaadin#2]
I have a Vaadin window with a button in it. Clicking it should change the caption of the button, then execute a long running task. Once that is done, the window should be closed.

I am trying to accomplish this with UITask but can't get it to work.
Here is a fairly minimal code example:

```
        Button btnOpenWindow = new Button("Open Window");

        final Window window = new MWindow().withClosable(true)
                .withResizable(true)
                .withModal(true)
                .withWidth("80em")
                .withCenter();

        Button btnTask = new Button("Long Running Task");
        btnTask.addClickListener(e -> {
            btnTask.setCaption("Working...");

            UITask<Integer> uiTask = new UITask<Integer>(new UIAccessor.Current()) {

                @Override
                protected Integer runInBackground() {
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException e1) {
                    }
                    return 1;
                }

                @Override
                protected void done() {
                    window.close();
                    btnTask.setCaption("Long Running Task");
                }
            };

            taskScheduler.schedule(uiTask, new Date());
        });

        btnOpenWindow.addClickListener(e -> {
            window.setContent(btnTask);
            UI.getCurrent().addWindow(window);
        });
```

While done() is executed, the window isn't closed and the button caption doesn't change.
When clicking the button again, the window is closed without runInBackground() or done() being called.

Am i using UITask wrong or is there a bug here?

**Comment by mpilone** [comment]
Are you using automatic PUSH for the transport? If not, you'll need to let the client know there were changes. If you're using manual push then you need to call push() on the UI. If you're not using push then the client will only see the changes on the next poll interval. Basically the client doesn't know the state of the UI changed on the server until the changes are pushed out or the client polls to get them.

**Comment by JohannesDorn** [comment]
I had not activated push. In fact, i was not aware of Vaadin's push mechanism at all. Thanks for introducing me! May i suggest adding a small comment about the need for Push to be enabled to the add-on's description in the Vaadin directory and to the README.md?

**Comment by mpilone** [comment]
Good suggestion. I've added some more documentation to the README in the develop branch. It will be included in the next release.
